# Generated by Django 4.2 on 2023-05-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spApp', '0004_rename_college_company_rename_course_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='college',
            new_name='company',
        ),
        migrations.AddField(
            model_name='job',
            name='desc',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
