# Generated by Django 4.2 on 2023-05-02 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spApp', '0005_rename_college_job_company_job_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='subcat',
        ),
        migrations.RemoveField(
            model_name='question',
            name='subcat',
        ),
        migrations.AddField(
            model_name='exam',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spApp.job'),
        ),
        migrations.AddField(
            model_name='question',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spApp.job'),
        ),
    ]
