# Generated by Django 4.2 on 2023-05-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spApp', '0006_remove_exam_subcat_remove_question_subcat_exam_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='video',
            field=models.FileField(null=True, upload_to='Exam'),
        ),
    ]
