# Generated by Django 4.2 on 2023-05-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spApp', '0007_exam_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='result2',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
